name       : perl-unicode-collate
version    : '1.27'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/S/SA/SADAHIRO/Unicode-Collate-1.27.tar.gz : 6e754b7ddcb37ceb0cce3a4dfc69f666c2b051484ba64e54dc26666f8825ae89
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Unicode::Collate - Unicode Collation Algorithm
description: |
    Unicode::Collate - Unicode Collation Algorithm
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
