name       : perl-unicode-collate
version    : 1.25
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/S/SA/SADAHIRO/Unicode-Collate-1.25.tar.gz : ddfbb8a08b60024f83136acc9027143df91a7d115120961686082aa5c964fbb6
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Unicode::Collate - Unicode Collation Algorithm
description: |
    Unicode::Collate - Unicode Collation Algorithm
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
