name       : perl-unicode-collate
version    : '1.31'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/S/SA/SADAHIRO/Unicode-Collate-1.31.tar.gz : b75dd07bbc252937b1b87064bf79ccd0a1b7ee993b8cf0e80f47406c3205639f
homepage   : https://metacpan.org/pod/Unicode::Collate
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Unicode::Collate - Unicode Collation Algorithm
description: |
    This module is an implementation of Unicode Technical Standard #10 (a.k.a. UTS #10) - Unicode Collation Algorithm (a.k.a. UCA).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
